/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import objects.Agendamento;
import connections.MySQL;
import javax.swing.JOptionPane;

/**
 *
 * @author annas
 */
public class CadastrarCliente extends javax.swing.JFrame {
        MySQL conectar = new MySQL();
        Agendamento novoAgendamento = new Agendamento();
    /**
     * Creates new form agendamento
     */
    public CadastrarCliente() {
        initComponents();
    }
    private void cadNovoAgendamento(Agendamento novoAgendamento){
    this.conectar.conectaBanco();
    
    novoAgendamento.setNome(txt_nome.getText());
    novoAgendamento.setTelefone(txt_telefone.getText());
    novoAgendamento.setEndereco(txt_endereco.getText());
    novoAgendamento.setGenero((String)cmb_genero.getSelectedItem());
    novoAgendamento.setIdade((String)cmb_idade.getSelectedItem());
    novoAgendamento.setCpf(txt_cpf.getText());
    

    //String Animal;String nomeDono;String telefone;String dia;String servico;
    
    try{
       this.conectar.insertSQL("INSERT INTO cliente ("
    + "nome,"
    + "telefone,"
    + "endereco,"
    + "genero,"
    + "idade,"
    + "cpf"
    + ") VALUES ("
    + "'" + novoAgendamento.getNome() + "',"
    + "'" + novoAgendamento.getTelefone() + "',"
    + "'" + novoAgendamento.getEndereco() + "',"
    + "'" + novoAgendamento.getGenero() + "',"
    + "'" + novoAgendamento.getIdade() + "',"
    + "'" + novoAgendamento.getCpf() + "'" 
    + ");");

     
     } catch (Exception e){
            System.err.println("Erro ao cadastrar cliente" + e.getMessage());
            JOptionPane.showMessageDialog(null, "Erro ao cadastrar cliente");
        } finally{
            this.conectar.fechaBanco();
            JOptionPane.showMessageDialog(null, "Cliente cadastrado com sucesso");
        }

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn_agendar = new javax.swing.JButton();
        jLabel_Servico = new javax.swing.JLabel();
        txt_nome = new javax.swing.JTextField();
        jLabel_Animal = new javax.swing.JLabel();
        cmb_genero = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        cmb_idade = new javax.swing.JComboBox<>();
        jLabel_Hora = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_cpf = new javax.swing.JFormattedTextField();
        txt_telefone = new javax.swing.JFormattedTextField();
        txt_endereco = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_agendamento = new javax.swing.JButton();
        btn_agenda1 = new javax.swing.JButton();
        btn_agenda2 = new javax.swing.JButton();
        btn_agenda3 = new javax.swing.JButton();
        btn_agenda6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(1039, 593));
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 63, 89));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Telefone:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(40, 110, 70, 20);

        btn_agendar.setBackground(new java.awt.Color(240, 140, 23));
        btn_agendar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_agendar.setForeground(new java.awt.Color(255, 255, 255));
        btn_agendar.setText("Cadastrar");
        btn_agendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agendarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_agendar);
        btn_agendar.setBounds(270, 460, 220, 40);

        jLabel_Servico.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_Servico.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Servico.setText("Endereço:");
        jPanel2.add(jLabel_Servico);
        jLabel_Servico.setBounds(40, 180, 70, 20);
        jPanel2.add(txt_nome);
        txt_nome.setBounds(40, 50, 240, 30);

        jLabel_Animal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_Animal.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Animal.setText("Gênero:");
        jPanel2.add(jLabel_Animal);
        jLabel_Animal.setBounds(310, 110, 61, 20);

        cmb_genero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino" }));
        cmb_genero.setFocusable(false);
        cmb_genero.setLightWeightPopupEnabled(false);
        cmb_genero.setRequestFocusEnabled(false);
        cmb_genero.setVerifyInputWhenFocusTarget(false);
        cmb_genero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_generoActionPerformed(evt);
            }
        });
        jPanel2.add(cmb_genero);
        cmb_genero.setBounds(310, 130, 240, 30);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("CPF:");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(310, 30, 61, 20);

        cmb_idade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "98", "99", "100", "101", "102", "103", "104", "105", "106", "107", "108", "109", "110", "111", "112", "113", "114", "115", "116", "117", "118", "119", "120" }));
        cmb_idade.setFocusable(false);
        cmb_idade.setLightWeightPopupEnabled(false);
        cmb_idade.setRequestFocusEnabled(false);
        cmb_idade.setVerifyInputWhenFocusTarget(false);
        cmb_idade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_idadeActionPerformed(evt);
            }
        });
        jPanel2.add(cmb_idade);
        cmb_idade.setBounds(310, 200, 240, 30);

        jLabel_Hora.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_Hora.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Hora.setText("Idade:");
        jPanel2.add(jLabel_Hora);
        jLabel_Hora.setBounds(310, 180, 61, 20);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Nome:");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(40, 30, 61, 20);

        try {
            txt_cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(txt_cpf);
        txt_cpf.setBounds(310, 50, 240, 30);

        try {
            txt_telefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(txt_telefone);
        txt_telefone.setBounds(40, 130, 240, 30);
        jPanel2.add(txt_endereco);
        txt_endereco.setBounds(40, 200, 240, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(220, 0, 840, 590);

        jPanel1.setBackground(new java.awt.Color(240, 140, 23));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("AGENDAR");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 70, 220, 30);

        btn_agendamento.setBackground(new java.awt.Color(231, 168, 95));
        btn_agendamento.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        btn_agendamento.setForeground(new java.awt.Color(255, 255, 255));
        btn_agendamento.setText("NOVO AGENDAMENTO");
        btn_agendamento.setBorder(null);
        btn_agendamento.setBorderPainted(false);
        btn_agendamento.setFocusPainted(false);
        btn_agendamento.setFocusable(false);
        btn_agendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agendamentoActionPerformed(evt);
            }
        });
        jPanel1.add(btn_agendamento);
        btn_agendamento.setBounds(0, 140, 220, 48);

        btn_agenda1.setBackground(new java.awt.Color(231, 168, 95));
        btn_agenda1.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        btn_agenda1.setForeground(new java.awt.Color(255, 255, 255));
        btn_agenda1.setText("EDITAR AGENDAMENTO");
        btn_agenda1.setBorder(null);
        btn_agenda1.setRequestFocusEnabled(false);
        btn_agenda1.setRolloverEnabled(false);
        btn_agenda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agenda1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_agenda1);
        btn_agenda1.setBounds(0, 190, 220, 48);

        btn_agenda2.setBackground(new java.awt.Color(231, 168, 95));
        btn_agenda2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_agenda2.setForeground(new java.awt.Color(255, 255, 255));
        btn_agenda2.setText("TABELA AGENDA");
        btn_agenda2.setBorder(null);
        btn_agenda2.setRequestFocusEnabled(false);
        btn_agenda2.setRolloverEnabled(false);
        btn_agenda2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agenda2ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_agenda2);
        btn_agenda2.setBounds(0, 240, 220, 48);

        btn_agenda3.setBackground(new java.awt.Color(255, 102, 51));
        btn_agenda3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_agenda3.setForeground(new java.awt.Color(255, 255, 255));
        btn_agenda3.setText("SAIR");
        btn_agenda3.setBorder(null);
        btn_agenda3.setRequestFocusEnabled(false);
        btn_agenda3.setRolloverEnabled(false);
        btn_agenda3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agenda3ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_agenda3);
        btn_agenda3.setBounds(0, 490, 220, 30);

        btn_agenda6.setBackground(new java.awt.Color(231, 168, 95));
        btn_agenda6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_agenda6.setForeground(new java.awt.Color(255, 255, 255));
        btn_agenda6.setText("TABELA CLIENTE");
        btn_agenda6.setBorder(null);
        btn_agenda6.setRequestFocusEnabled(false);
        btn_agenda6.setRolloverEnabled(false);
        btn_agenda6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agenda6ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_agenda6);
        btn_agenda6.setBounds(0, 290, 220, 48);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 220, 590);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btn_agendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agendarActionPerformed
        cadNovoAgendamento(novoAgendamento);
    }//GEN-LAST:event_btn_agendarActionPerformed

    private void cmb_generoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_generoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_generoActionPerformed

    private void cmb_idadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_idadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_idadeActionPerformed

    private void btn_agendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agendamentoActionPerformed
        CadastrarCliente agendament = new CadastrarCliente();
        agendament.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_agendamentoActionPerformed

    private void btn_agenda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agenda1ActionPerformed
        PesquisarAtualizarDeletarAgendamento agend = new PesquisarAtualizarDeletarAgendamento();
        agend.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_agenda1ActionPerformed

    private void btn_agenda2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agenda2ActionPerformed
        TabelaAgendamento agend = new TabelaAgendamento();
        agend.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_agenda2ActionPerformed

    private void btn_agenda3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agenda3ActionPerformed
        login agend = new login();
        agend.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_agenda3ActionPerformed

    private void btn_agenda6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agenda6ActionPerformed
        TabelaClienteInfo agend = new TabelaClienteInfo();
        agend.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_agenda6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agenda1;
    private javax.swing.JButton btn_agenda2;
    private javax.swing.JButton btn_agenda3;
    private javax.swing.JButton btn_agenda6;
    private javax.swing.JButton btn_agendamento;
    private javax.swing.JButton btn_agendar;
    private javax.swing.JComboBox<String> cmb_genero;
    private javax.swing.JComboBox<String> cmb_idade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_Animal;
    private javax.swing.JLabel jLabel_Hora;
    private javax.swing.JLabel jLabel_Servico;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JFormattedTextField txt_cpf;
    private javax.swing.JTextField txt_endereco;
    private javax.swing.JTextField txt_nome;
    private javax.swing.JFormattedTextField txt_telefone;
    // End of variables declaration//GEN-END:variables

    

        
    

    
    
}
