/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import objects.Agendamento;
import connections.MySQL;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author annas
 */
public class CadastrarAgendamento extends javax.swing.JFrame {
        MySQL conectar = new MySQL();
        Agendamento novoAgendamento = new Agendamento();
    /**
     * Creates new form agendamento
     */
    public CadastrarAgendamento() {
        initComponents();
    }
    private void cadNovoAgendamento(Agendamento novoAgendamento){
    this.conectar.conectaBanco();
    Date d = null;
    DateFormat data = new SimpleDateFormat("dd/MM/yyyy" );
     try{
        d = data.parse(data.format(jCalendar.getDate()));
    } catch(Exception e){
           e.printStackTrace();
       }
    novoAgendamento.setNome(txt_nome.getText());
    novoAgendamento.setTelefone(txt_telefone.getText());
    novoAgendamento.setServico((String)cmb_servico.getSelectedItem());
    novoAgendamento.setHora((String)cmb_hora.getSelectedItem());
    novoAgendamento.setValor((String)cmb_valor.getSelectedItem());
    novoAgendamento.setAgenda(data.format(d));
    novoAgendamento.setCpf(txt_cpf.getText());
    txt_agendamento.setText(novoAgendamento.getAgenda());

    //String Animal;String nomeDono;String telefone;String dia;String servico;
    
    try{
        this.conectar.insertSQL("INSERT INTO agendamento("
    + "nome,"
    + "telefone,"
    + "servico,"
    + "hora,"
    + "valor,"
    + "agenda,"
    + "cpf"
    + ")VALUES("
    + "'" +novoAgendamento.getNome()+"',"
    + "'" +novoAgendamento.getTelefone()+ "',"
    + "'" +novoAgendamento.getServico()+"',"
    + "'" +novoAgendamento.getHora()+ "',"
    + "'" +novoAgendamento.getValor()+ "',"
    + "'" +novoAgendamento.getAgenda()+ "',"
    + "'" +novoAgendamento.getCpf()+ "'" 
    + ");");
     } catch (Exception e){
            System.err.println("Erro ao cadastrar Agendamento" + e.getMessage());
            JOptionPane.showMessageDialog(null, "Erro ao cadastrar agendamento");
        } finally{
            this.conectar.fechaBanco();
            JOptionPane.showMessageDialog(null, "Usuario agendado com sucesso");
        }

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn_agendar = new javax.swing.JButton();
        jLabel_Servico = new javax.swing.JLabel();
        txt_nome = new javax.swing.JTextField();
        jLabel_Animal = new javax.swing.JLabel();
        jLabel_Nome_Dono = new javax.swing.JLabel();
        cmb_valor = new javax.swing.JComboBox<>();
        cmb_servico = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        cmb_hora = new javax.swing.JComboBox<>();
        jLabel_Hora = new javax.swing.JLabel();
        jCalendar = new com.toedter.calendar.JCalendar();
        txt_agendamento = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_cpf = new javax.swing.JFormattedTextField();
        txt_telefone = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_agendamento = new javax.swing.JButton();
        btn_agenda1 = new javax.swing.JButton();
        btn_agenda2 = new javax.swing.JButton();
        btn_agenda3 = new javax.swing.JButton();
        btn_agenda6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1039, 593));
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 63, 89));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Telefone:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(40, 150, 70, 20);

        btn_agendar.setBackground(new java.awt.Color(240, 140, 23));
        btn_agendar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_agendar.setForeground(new java.awt.Color(255, 255, 255));
        btn_agendar.setText("Agendar");
        btn_agendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agendarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_agendar);
        btn_agendar.setBounds(270, 460, 220, 40);

        jLabel_Servico.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_Servico.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Servico.setText("Serviço:");
        jPanel2.add(jLabel_Servico);
        jLabel_Servico.setBounds(40, 270, 61, 20);
        jPanel2.add(txt_nome);
        txt_nome.setBounds(40, 50, 240, 30);

        jLabel_Animal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_Animal.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Animal.setText("Valor:");
        jPanel2.add(jLabel_Animal);
        jLabel_Animal.setBounds(40, 210, 61, 20);

        jLabel_Nome_Dono.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_Nome_Dono.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Nome_Dono.setText("Data:");
        jPanel2.add(jLabel_Nome_Dono);
        jLabel_Nome_Dono.setBounds(320, 270, 110, 20);

        cmb_valor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "R$ 10,00", "R$ 20,00", "R$ 30,00", "R$ 40,00", "R$ 50,00", "R$ 60,00", "R$ 70,00", "R$ 80,00", "R$ 90,00", "R$ 100,00", "R$ 110,00", "R$ 120,00", "R$ 130,00", "R$ 140,00", "R$ 150,00", "R$ 150,00", "R$ 160,00", "R$ 170,00", "R$ 180,00", "R$ 190,00", "R$ 200,00", "R$ 210,00", "R$ 220,00", "R$ 230,00", "R$ 240,00", "R$ 250,00", "R$ 260,00", "R$ 270,00", "R$ 280,00", "R$ 290,00", "R$ 300,00" }));
        cmb_valor.setFocusable(false);
        cmb_valor.setLightWeightPopupEnabled(false);
        cmb_valor.setRequestFocusEnabled(false);
        cmb_valor.setVerifyInputWhenFocusTarget(false);
        cmb_valor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_valorActionPerformed(evt);
            }
        });
        jPanel2.add(cmb_valor);
        cmb_valor.setBounds(40, 230, 110, 30);

        cmb_servico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cabelo Masculino", "Pezinho", "Barba", "Cabelo Masculino & Barba", "Barba & Pezinho", "Cabelo Feminino", "Sobrancelha", "Cilios", "Cabelo F & Sobrancelha", "Cabelo F & Cilios", "Cabelo F & Sobrancelha & Cilios", "Sobrancelha & Cilios" }));
        cmb_servico.setFocusable(false);
        cmb_servico.setLightWeightPopupEnabled(false);
        cmb_servico.setRequestFocusEnabled(false);
        cmb_servico.setVerifyInputWhenFocusTarget(false);
        cmb_servico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_servicoActionPerformed(evt);
            }
        });
        jPanel2.add(cmb_servico);
        cmb_servico.setBounds(40, 290, 240, 30);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("CPF:");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(40, 90, 61, 20);

        cmb_hora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8:00", "9:00", "10:00", "11:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00" }));
        cmb_hora.setFocusable(false);
        cmb_hora.setLightWeightPopupEnabled(false);
        cmb_hora.setRequestFocusEnabled(false);
        cmb_hora.setVerifyInputWhenFocusTarget(false);
        cmb_hora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_horaActionPerformed(evt);
            }
        });
        jPanel2.add(cmb_hora);
        cmb_hora.setBounds(170, 230, 110, 30);

        jLabel_Hora.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel_Hora.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Hora.setText("Horário:");
        jPanel2.add(jLabel_Hora);
        jLabel_Hora.setBounds(170, 210, 61, 20);
        jPanel2.add(jCalendar);
        jCalendar.setBounds(320, 50, 450, 210);

        txt_agendamento.setEnabled(false);
        txt_agendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_agendamentoActionPerformed(evt);
            }
        });
        jPanel2.add(txt_agendamento);
        txt_agendamento.setBounds(320, 290, 110, 30);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Nome:");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(40, 30, 61, 20);

        try {
            txt_cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(txt_cpf);
        txt_cpf.setBounds(40, 110, 240, 30);

        try {
            txt_telefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel2.add(txt_telefone);
        txt_telefone.setBounds(40, 170, 240, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(220, 0, 850, 590);

        jPanel1.setBackground(new java.awt.Color(240, 140, 23));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("AGENDAR");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 70, 220, 30);

        btn_agendamento.setBackground(new java.awt.Color(231, 168, 95));
        btn_agendamento.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        btn_agendamento.setForeground(new java.awt.Color(255, 255, 255));
        btn_agendamento.setText("NOVO AGENDAMENTO");
        btn_agendamento.setBorder(null);
        btn_agendamento.setBorderPainted(false);
        btn_agendamento.setFocusPainted(false);
        btn_agendamento.setFocusable(false);
        btn_agendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agendamentoActionPerformed(evt);
            }
        });
        jPanel1.add(btn_agendamento);
        btn_agendamento.setBounds(0, 140, 220, 48);

        btn_agenda1.setBackground(new java.awt.Color(231, 168, 95));
        btn_agenda1.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        btn_agenda1.setForeground(new java.awt.Color(255, 255, 255));
        btn_agenda1.setText("EDITAR AGENDAMENTO");
        btn_agenda1.setBorder(null);
        btn_agenda1.setRequestFocusEnabled(false);
        btn_agenda1.setRolloverEnabled(false);
        btn_agenda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agenda1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_agenda1);
        btn_agenda1.setBounds(0, 190, 220, 48);

        btn_agenda2.setBackground(new java.awt.Color(231, 168, 95));
        btn_agenda2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_agenda2.setForeground(new java.awt.Color(255, 255, 255));
        btn_agenda2.setText("TABELA AGENDA");
        btn_agenda2.setBorder(null);
        btn_agenda2.setRequestFocusEnabled(false);
        btn_agenda2.setRolloverEnabled(false);
        btn_agenda2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agenda2ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_agenda2);
        btn_agenda2.setBounds(0, 240, 220, 48);

        btn_agenda3.setBackground(new java.awt.Color(255, 102, 51));
        btn_agenda3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_agenda3.setForeground(new java.awt.Color(255, 255, 255));
        btn_agenda3.setText("SAIR");
        btn_agenda3.setBorder(null);
        btn_agenda3.setRequestFocusEnabled(false);
        btn_agenda3.setRolloverEnabled(false);
        btn_agenda3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agenda3ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_agenda3);
        btn_agenda3.setBounds(0, 490, 220, 30);

        btn_agenda6.setBackground(new java.awt.Color(231, 168, 95));
        btn_agenda6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_agenda6.setForeground(new java.awt.Color(255, 255, 255));
        btn_agenda6.setText("TABELA USUARIO");
        btn_agenda6.setBorder(null);
        btn_agenda6.setRequestFocusEnabled(false);
        btn_agenda6.setRolloverEnabled(false);
        btn_agenda6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agenda6ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_agenda6);
        btn_agenda6.setBounds(0, 290, 220, 48);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 220, 590);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btn_agendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agendarActionPerformed
        cadNovoAgendamento(novoAgendamento);
    }//GEN-LAST:event_btn_agendarActionPerformed

    private void cmb_servicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_servicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_servicoActionPerformed

    private void cmb_valorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_valorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_valorActionPerformed

    private void cmb_horaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_horaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_horaActionPerformed

    private void txt_agendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_agendamentoActionPerformed

    }//GEN-LAST:event_txt_agendamentoActionPerformed

    private void btn_agendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agendamentoActionPerformed
        CadastrarAgendamento agendament = new CadastrarAgendamento();
        agendament.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_agendamentoActionPerformed

    private void btn_agenda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agenda1ActionPerformed
        PesquisarAtualizarDeletarAgendamento agend = new PesquisarAtualizarDeletarAgendamento();
        agend.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_agenda1ActionPerformed

    private void btn_agenda2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agenda2ActionPerformed
        TabelaAgendamento agend = new TabelaAgendamento();
        agend.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_agenda2ActionPerformed

    private void btn_agenda3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agenda3ActionPerformed
        Login agend = new Login();
        agend.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_agenda3ActionPerformed

    private void btn_agenda6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agenda6ActionPerformed
        TabelaClienteInfo agend = new TabelaClienteInfo();
        agend.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_agenda6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarAgendamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarAgendamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agenda1;
    private javax.swing.JButton btn_agenda2;
    private javax.swing.JButton btn_agenda3;
    private javax.swing.JButton btn_agenda6;
    private javax.swing.JButton btn_agendamento;
    private javax.swing.JButton btn_agendar;
    private javax.swing.JComboBox<String> cmb_hora;
    private javax.swing.JComboBox<String> cmb_servico;
    private javax.swing.JComboBox<String> cmb_valor;
    private com.toedter.calendar.JCalendar jCalendar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_Animal;
    private javax.swing.JLabel jLabel_Hora;
    private javax.swing.JLabel jLabel_Nome_Dono;
    private javax.swing.JLabel jLabel_Servico;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txt_agendamento;
    private javax.swing.JFormattedTextField txt_cpf;
    private javax.swing.JTextField txt_nome;
    private javax.swing.JFormattedTextField txt_telefone;
    // End of variables declaration//GEN-END:variables

    

        
    

    
    
}
